# Generated by Django 3.2.9 on 2021-11-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_millonaria_dolares', models.FloatField()),
                ('tipo_de_cambio', models.FloatField()),
                ('cuenta_millonaria_soles', models.FloatField()),
                ('cuenta_AFP_soles', models.FloatField(default=0)),
                ('cuenta_ahorro_soles', models.FloatField()),
                ('cuenta_sueldo_soles', models.FloatField()),
                ('fecha', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
