# Generated by Django 3.2.9 on 2021-11-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorroapp', '0002_auto_20211115_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='fecha',
            field=models.DateField(),
        ),
    ]
